### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Mr-Lawrence-521** [TomSkelly/MatchAnnot#16]
After I changed the python version into python2.7 and run the matchannot.py, I got the error below:
Traceback (most recent call last):
  File "MatchAnnot-master/matchAnnot.py", line 540, in <module>
    main()
  File "MatchAnnot-master/matchAnnot.py", line 49, in main
    annotList = anno.AnnotationList (opt.gtf)
  File "/public/home/guolang/MatchAnnot-master/Annotations.py", line 128, in __init__
    self.initFromStandard()
  File "/public/home/guolang/MatchAnnot-master/Annotations.py", line 174, in initFromStandard
    geneName = re.search(regexGene, attrs).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Does anyone encounter this problem？

**Comment by jeffstulberg** [comment]
I ran into the same issue when using python 2.7.18. Did you resolve this issue?

**Comment by jeffstulberg** [comment]
I ran into that issue when specifying the incorrect format of the annotation file that I was using. Try changing it.

**Comment by MrLawrence111111111** [comment]
Sorry for reply this late. Thank you for help ！I created a new environment and install a python=2.7 and used MatchAnnot in it and no more error occurred. Thank you very much for sharing.


发件人: jeffstulberg
发送时间: 2023年8月10日 19:35
收件人: TomSkelly/MatchAnnot
抄送: Lang; Author
主题: Re: [TomSkelly/MatchAnnot] AttributeError: 'NoneType' object has noattribute 'group' (Issue #16)

I ran into that issue when specifying the incorrect format of the annotation file that I was using. Try changing it.

**Comment by Mr-Lawrence-521** [comment]
> I ran into that issue when specifying the incorrect format of the annotation file that I was using. Try changing it.

Thank you for help ！I created a new environment and install a python=2.7 and used MatchAnnot in it and no more error occurred. Thank you very much for sharing.
