### ISSUE TITLE
clusterView Error

### ISSUE THREAD

**Issue by yuanyongxian** [TomSkelly/MatchAnnot#4]
Hi Tom,
We were using matchAnnot and clusterView for PacBio ISO-Seq. MatchAnnot worked fine, however, clusterView returned with error:

Traceback (most recent call last):
  File "/ifs4/BC_RD/USER/shizhuoxing/bin/tofu/MatchAnnot-master/clusterView.py", line 805, in <module>
    main()
  File "/ifs4/BC_RD/USER/shizhuoxing/bin/tofu/MatchAnnot-master/clusterView.py", line 59, in main
    getGeneFromMatches (opt, tranList, exonList)       # lists will be changed
  File "/ifs4/BC_RD/USER/shizhuoxing/bin/tofu/MatchAnnot-master/clusterView.py", line 187, in getGeneFromMatches
    raise RuntimeError ('no length in name: %s' % cluster.name)
RuntimeError: no length in name: c930/f10p6/1846

We tried to plot several different genes, but it always returned with similar error.

Here is what we did:
(1). Aligned transcripts to genome with GMAP:
gmap -D hg19 -d hg19 -f samse -t 24 -n 0 all_quivered_hq.fastq >all_quivered_hq.fastq.sam
sorted all_quivered_hq.fastq.sam

(2). Used matchAnnot to find alternative splicing:
matchAnnot.py --gtf gencode.v19.annotation.gtf  all_quivered_hq.fastq.sam --outpickle annotations.pickle > annotations.out
*Till this step, everything seems worked well.

(3). Used clusterView to plot the result:
clusterView.py --gtf gencode.v19.annotation.gtf --matches annotations.pickle --gene ACTB --details out.txt  --output  out.png 
(Then returned with error as described at the beginning.)

Do you have any idea how this happened?
Looking forward to your reply.

Thanks.
Yuan

**Comment by TomSkelly** [comment]
Sorry, my fault. I'll put a fix up later today.

--TS

**Comment by 52teth** [comment]
the same error for me /(ㄒoㄒ)/~~

**Comment by 52teth** [comment]
Hello ,TomSkelly!
The same error troubles me. Here is the error:

File "/share/nas3/tengh/software/MatchAnnot/clusterView.py", line 805, in <module>
    main()
  File "/share/nas3/tengh/software/MatchAnnot/clusterView.py", line 59, in main
    getGeneFromMatches (opt, tranList, exonList)       # lists will be changed
  File "/share/nas3/tengh/software/MatchAnnot/clusterView.py", line 187, in getGeneFromMatches
    raise RuntimeError ('no length in name: %s' % cluster.name)
RuntimeError: no length in name: c116/f5p10/8698

Is there any advice for fixing this error?
Thanks a lot !
huan

**Comment by yuanyongxian** [comment]
Hi Tom, did you fix the error? We are waiting for you update.

**Comment by 52teth** [comment]
It seems like that the line 41 in MatchAnnot/clusterView.py is error,you can fix it to "REGEX_LEN  = re.compile ('\/(\d+)$')    # cluster length in cluster name" .

**Comment by yuanyongxian** [comment]
Thanks Huan! It works in our project.

Yuan
