### ISSUE TITLE
matchAnnot error on genome with scaffolds

### ISSUE THREAD

**Issue by atulkakrana** [TomSkelly/MatchAnnot#5]
Hi Tom,

I am using machAnnot on a draft genome, which has lot of scaffolds that I renamed as 'chr'. Here is the error:

[DEBUG] 2015-10-02 13:36:31,287 [Annotations 227] reading annotations in alternate format from AsOf.V2.modified.gtf
[DEBUG] 2015-10-02 13:36:35,051 [Annotations 319] read 35182 genes, 35182 transcripts, 151489 exons
[DEBUG] 2015-10-02 13:36:35,057 [matchAnnot 60] reading SAM file Aspar_1-3all_ref_polished_high_qv_consensus_isoforms.mod.sorted.sam
Traceback (most recent call last):
  File "/data1/homes/kakrana/tools/matchAnnot/matchAnnot.py", line 540, in <module>
    main()
  File "/data1/homes/kakrana/tools/matchAnnot/matchAnnot.py", line 161, in main
    annotCursor.advance (chr, start)
  File "/data1/homes/kakrana/tools/matchAnnot/Annotations.py", line 454, in advance
    geneList = self.annotList.geneList (chr)
  File "/data1/homes/kakrana/tools/matchAnnot/Annotations.py", line 359, in geneList
    raise RuntimeError ('chromosome %s not in annotation' % chr)
RuntimeError: chromosome chr10056 not in annotation

I guess MatchAnnot expects gene entries in GTF file, from every chromosome, which is true for final polished genomes. But in case of draft genomes with lots of scaffolds, some smaller scaffolds might not have any gene locus so no gene entry corresponding to such scaffolds in the annotations. Maybe, we can label such PacBio transcripts as 'no gene found'. 

Can you help me with this error?

Atul

**Comment by atulkakrana** [comment]
Hi Tom,

Any possibility of this issue being addressed? I would really appreciate it.

Atul

**Comment by thomasae** [comment]
Hi Tom,

Same problem here. Is there a way to modify the code so it skips the chromosomes that don't have annotated genes? 

Thanks in advance!
Thomas

/Resources/thomas/matchAnnot.py --gtf /fastdisk3/isoforms/gencode_grch37.13/gencode.v19.chr_patch_hapl_scaff.annotation.gtf --format standard --outpickle Unique_pickle /fastdisk3/thomas/pacbio/post_analysis/016441/STARalignment/sjdboverhang_100/Unique_Aligned.sortedByCoord.out.sam > Unique_annotations.out
[DEBUG] 2015-12-09 17:30:51,121 [Annotations 13] version 20150611.01 loaded
[DEBUG] 2015-12-09 17:30:51,121 [Cluster 13] version 20150814.01 loaded
[DEBUG] 2015-12-09 17:30:51,122 [ClusterReport 11] version 20141029.01 loaded
[DEBUG] 2015-12-09 17:30:51,123 [CigarString 15] version 20150707.01 loaded
[DEBUG] 2015-12-09 17:30:51,124 [PolyA 17] version 20150402.01 loaded
[DEBUG] 2015-12-09 17:30:51,124 [matchAnnot 37] version 20150611.02 starting
[DEBUG] 2015-12-09 17:30:51,125 [Annotations 134] reading annotations in standard format from /fastdisk3/isoforms/gencode_grch37.13/gencode.v19.chr_patch_hapl_scaff.annotation.gtf
[DEBUG] 2015-12-09 17:32:06,592 [Annotations 213] read 63568 genes, 214084 transcripts, 1296345 exons
[DEBUG] 2015-12-09 17:32:06,594 [matchAnnot 60] reading SAM file /fastdisk3/thomas/pacbio/post_analysis/016441/STARalignment/sjdboverhang_100/Unique_Aligned.sortedByCoord.out.sam
Traceback (most recent call last):
  File "/Resources/thomas/matchAnnot.py", line 540, in <module>
    main()
  File "/Resources/thomas/matchAnnot.py", line 161, in main
    annotCursor.advance (chr, start)
  File "/fastdisk3/thomas/pacbio/MatchAnnot-master/Annotations.py", line 454, in advance
    geneList = self.annotList.geneList (chr)
  File "/fastdisk3/thomas/pacbio/MatchAnnot-master/Annotations.py", line 359, in geneList
    raise RuntimeError ('chromosome %s not in annotation' % chr)
RuntimeError: chromosome GL000249.1 not in annotation
