### ISSUE TITLE
IndexError:

### ISSUE THREAD

**Issue by SongJiaMing1** [TomSkelly/MatchAnnot#9]
Dear TomSkelly:
     I am sorry to disturb you.when I use the MatchAnnot, it appear IndexError.
there is the log:
  [DEBUG] 2016-01-18 19:17:16,399 [Annotations 13] version 20150611.01 loaded
[DEBUG] 2016-01-18 19:17:16,402 [Cluster 13] version 20150814.01 loaded
[DEBUG] 2016-01-18 19:17:16,404 [ClusterReport 11] version 20141029.01 loaded
[DEBUG] 2016-01-18 19:17:16,406 [CigarString 15] version 20150707.01 loaded
[DEBUG] 2016-01-18 19:17:16,410 [PolyA 17] version 20150402.01 loaded
[DEBUG] 2016-01-18 19:17:16,410 [matchAnnot 37] version 20150611.02 starting
[DEBUG] 2016-01-18 19:17:16,412 [Annotations 227] reading annotations in alternate format from /home/jmsong/software/STAR-STAR_2.4.2a/bin/Linux_x86_64/data/mh63_test_2.gtf
[DEBUG] 2016-01-18 19:17:35,341 [Annotations 319] read 57174 genes, 80579 transcripts, 421606 exons
[DEBUG] 2016-01-18 19:17:35,342 [matchAnnot 60] reading SAM file /home/jmsong/software/STAR-STAR_2.4.2a/bin/Linux_x86_64/MH_test_shortAligned.out.sam
Traceback (most recent call last):
  File "./matchAnnot.py", line 540, in <module>
    main()
  File "./matchAnnot.py", line 124, in main
    exons = cigar.exons()
  File "/home/jmsong/software/MatchAnnot-master/CigarString.py", line 189, in exons
    self.variants.append ( ['D', count, exonList[-1].end+1, offset+exonList[-1].size, cf[2]] )     # +1: end is inclusive
IndexError: tuple index out of range

how can i fix it ?  Look forward to your kind adive.

**Comment by markopetek** [comment]
I'm getting the same error. I've mapped the reads with STAR_2.6.1d.

[DEBUG] 2019-05-28 15:16:17,668 [Annotations 13] version 20150611.01 loaded
[DEBUG] 2019-05-28 15:16:17,669 [Cluster 13] version 20150814.01 loaded
[DEBUG] 2019-05-28 15:16:17,670 [ClusterReport 11] version 20141029.01 loaded
[DEBUG] 2019-05-28 15:16:17,670 [CigarString 15] version 20150707.01 loaded
[DEBUG] 2019-05-28 15:16:17,671 [PolyA 17] version 20150402.01 loaded
[DEBUG] 2019-05-28 15:16:17,671 [matchAnnot 37] version 20150611.02 starting
[DEBUG] 2019-05-28 15:16:17,672 [Annotations 227] reading annotations in alternate format from ./input/Planococcus_citri_Pcitri.v1.gtf
[DEBUG] 2019-05-28 15:16:21,982 [Annotations 319] read 57832 genes, 59472 transcripts, 198187 exons
[DEBUG] 2019-05-28 15:16:21,995 [matchAnnot 60] reading SAM file ./STAR_mapSpadesTRtoGenome/PcSpadesTRsofttoGenome_STARlong_Aligned.sorted2.out.sam
Traceback (most recent call last):
  File "/home/administrator/Software/MatchAnnot/matchAnnot.py", line 540, in <module>
    main()
  File "/home/administrator/Software/MatchAnnot/matchAnnot.py", line 124, in main
    exons = cigar.exons()
  File "/home/administrator/Software/MatchAnnot/CigarString.py", line 189, in exons
    self.variants.append ( ['D', count, exonList[-1].end+1, offset+exonList[-1].size, cf[2]] )     # +1: end is inclusive
IndexError: tuple index out of range

**Comment by tay45** [comment]
Hello,

I have the same issue. Could you please give me a comment? 

$ ../MatchAnnot/matchAnnot.py --gtf gencode.v30.annotation.gtf polished.hq.fastq.sorted.sam > polished.hq.fastq.sorted.sam.matchAnnot.txt
[DEBUG] 2019-06-11 17:52:28,886 [Annotations 13] version 20150611.01 loaded
[DEBUG] 2019-06-11 17:52:28,886 [Cluster 13] version 20150814.01 loaded
[DEBUG] 2019-06-11 17:52:28,886 [ClusterReport 11] version 20141029.01 loaded
[DEBUG] 2019-06-11 17:52:28,887 [CigarString 15] version 20150707.01 loaded
[DEBUG] 2019-06-11 17:52:28,888 [PolyA 17] version 20150402.01 loaded
[DEBUG] 2019-06-11 17:52:28,888 [matchAnnot 37] version 20150611.02 starting
[DEBUG] 2019-06-11 17:52:28,888 [Annotations 134] reading annotations in standard format from /Volumes/Seq/PacBio/thkang/lili_wang_iso-seq/gencode.v30.annotation.gtf
[DEBUG] 2019-06-11 17:54:37,105 [Annotations 213] read 58870 genes, 208621 transcripts, 1279686 exons
[DEBUG] 2019-06-11 17:54:37,106 [matchAnnot 60] reading SAM file /Volumes/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/gencode_version/aligned/nalm6k_polished.hq.fastq.sorted.sam
Traceback (most recent call last):
  File "/Users/THKang/MatchAnnot/matchAnnot.py", line 540, in <module>
    main()
  File "/Users/THKang/MatchAnnot/matchAnnot.py", line 124, in main
    exons = cigar.exons()
  File "/Users/THKang/MatchAnnot/CigarString.py", line 189, in exons
    self.variants.append ( ['D', count, exonList[-1].end+1, offset+exonList[-1].size, cf[2]] )     # +1: end is inclusive
IndexError: tuple index out of range

**Comment by tky199996** [comment]
Hello, I encountered the same problem recently. I used pbmm2 for comparison and got the sorted bam file. Then I converted the bam file format to a sam file, and then used python2.7 ~/MatchAnnot- master/matchAnnot.py --gtf ../../12.ref/genes.gtf ../../41.map_LR_to_genome/41.brain/brain.sam --format alt > annotations.out Code running, get Got the same error as them, have you solved this problem? If so, can you tell me where the problem occurred? Thank you for your help
Traceback (most recent call last):
  File "/home/tianky/MatchAnnot-master/matchAnnot.py", line 540, in <module>
    main()
  File "/home/tianky/MatchAnnot-master/matchAnnot.py", line 124, in main
    exons = cigar.exons()
  File "/home/tianky/MatchAnnot-master/CigarString.py", line 189, in exons
    self.variants.append ( ['D', count, exonList[-1].end+1, offset+exonList[-1].size, cf[2]] )     # +1: end is inclusive
IndexError: tuple index out of range
